# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peerID', models.CharField(max_length=200)),
                ('creatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorID', to=settings.AUTH_USER_MODEL)),
                ('joinerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joinerID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
