# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20160409_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='peerID',
            new_name='peerCreatorID',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='peerJoinerID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
